GET http://localhost:8080/currencies
###

POST http://localhost:8080/currencies
Content-Type: application/json

{
  "fullName": "Yan",
  "code": "YAN",
  "sign": "U"
}
###
GET http://localhost:8080/currency/USD
####
GET http://localhost:8080/exchangeRate/USDRUB
####
GET http://localhost:8080/exchangeRate/RUBUSD
####
PATCH http://localhost:8080/exchangeRate/USDRUB?rate=91.2
####
#
GET http://localhost:8080/exchangeRates
####
POST http://localhost:8080/exchangeRates?baseCurrencyCode=US&targetCurrencyCode=RUB&rate=90.15
####
#
GET http://localhost:8080/exchange
####

GET  http://localhost:8080/exchange?from=RUB&to=USD&amount=91.2
#
